--用户表
CREATE TABLE NVC_USERINFO
(
    ID          NUMBER(20,0) NOT NULL ENABLE,
    USERNO     VARCHAR2(20 BYTE),
    USERPWD VARCHAR2(20),
    USERSTATUS NUMBER(10),
    USERNAME VARCHAR2(50 BYTE),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(20),
    AGE VARCHAR2(20),
    SEX VARCHAR2(20),
	CONSTRAINT PK_NVC_USERINFO PRIMARY KEY (ID)
);
COMMENT ON COLUMN NVC_USERINFO.ID IS '主键id';
COMMENT ON COLUMN NVC_USERINFO.USERNO IS '用户账户';
COMMENT ON COLUMN NVC_USERINFO.USERPWD IS '用户密码';
COMMENT ON COLUMN NVC_USERINFO.USERSTATUS IS '用户状态';
COMMENT ON COLUMN NVC_USERINFO.USERNAME IS '用户姓名';
COMMENT ON COLUMN NVC_USERINFO.PHONE IS '手机号';
COMMENT ON COLUMN NVC_USERINFO.ADDRESS IS '地址';
COMMENT ON COLUMN NVC_USERINFO.AGE IS '年级';
COMMENT ON COLUMN NVC_USERINFO.SEX IS '性别';